"""BDX-021 drift monitoring: alerts only, never auto-deploy.

Compare feature / measured-target / prediction windows with the immutable
snapshot a production model was trained on. A human promotes via the
BDX-020 registry. Drift never silently swaps the live model.
"""
from intelligence.drift.monitor import DriftCheckError, check_production_model, compare_windows
from intelligence.drift.persistence import (
    DriftNotFoundError,
    ImmutableDriftError,
    InvalidDriftError,
    acknowledge_alert,
    get_alert,
    get_report,
    list_alerts,
    list_reports,
    save_report,
)
from intelligence.drift.types import (
    ACTION_ALERT_ONLY,
    ACTION_HUMAN_PROMOTE,
    DATA_ROLES,
    DRIFT_KINDS,
    DRIFT_SEVERITIES,
    KIND_FEATURE,
    KIND_PREDICTION,
    KIND_TARGET,
    ROLE_DESIGNED,
    ROLE_EXECUTED,
    ROLE_MEASURED,
    ROLE_PREDICTED,
    SEVERITY_ALERT,
    SEVERITY_OK,
    SEVERITY_WATCH,
    DriftAlert,
    DriftMetric,
    DriftReport,
    listed_kinds,
    listed_severities,
    normalize_kind,
    normalize_severity,
)

__all__ = [
    "ACTION_ALERT_ONLY",
    "ACTION_HUMAN_PROMOTE",
    "DATA_ROLES",
    "DRIFT_KINDS",
    "DRIFT_SEVERITIES",
    "KIND_FEATURE",
    "KIND_PREDICTION",
    "KIND_TARGET",
    "ROLE_DESIGNED",
    "ROLE_EXECUTED",
    "ROLE_MEASURED",
    "ROLE_PREDICTED",
    "SEVERITY_ALERT",
    "SEVERITY_OK",
    "SEVERITY_WATCH",
    "DriftAlert",
    "DriftCheckError",
    "DriftMetric",
    "DriftNotFoundError",
    "DriftReport",
    "ImmutableDriftError",
    "InvalidDriftError",
    "acknowledge_alert",
    "check_production_model",
    "compare_windows",
    "get_alert",
    "get_report",
    "list_alerts",
    "list_reports",
    "listed_kinds",
    "listed_severities",
    "normalize_kind",
    "normalize_severity",
    "save_report",
]
